### ISSUE TITLE
Hack removal - libethereum

### ISSUE THREAD

**Issue by yep** [doublethinkco/cpp-ethereum-cross#107]
- Hacking out optional dependencies - ethash-cl, Cpuid, miniupnpc (all in main.sh)
 - BuildInfo.h and ConfigInfo.h aren't being installed properly, it seems?
 - Can we remove "homogenization" of outputs?

**Comment by bobsummerwill** [comment]
Subsumed into https://github.com/doublethinkco/cpp-ethereum-cross/issues/108
