### ISSUE TITLE
Eliminate hacks.  Upstream fixes

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/cpp-ethereum-cross#11]

**Comment by bobsummerwill** [comment]
Yeah ... Please could you break this up into a bug per hack?   Pain in the ass, I know, but working through these may take some time, and I don't want a mega-bug.   Thanks!

**Comment by anthony-cros** [comment]
Here's a breakdown:

# boost:
- setting gcc compiler [manually](https://github.com/doublethinkco/webthree-umbrella/blob/e1fbe8a/cross-build/ethereum/boost.sh#L26)

# curl:
- pointing to our gcc [explicitly](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/curl.sh#L15)

# jsoncpp:
- extra link [required](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/jsoncpp.sh#L48)

# cryptopp:
- manually remove ["native"](https://github.com/doublethinkco/webthree-umbrella/blob/e1fbe8ad4974fa257079f6b9469611dceb835ee8/cross-build/ethereum/cryptopp.sh#L22)
- extra links needed: [1](https://github.com/doublethinkco/webthree-umbrella/blob/e1fbe8ad4974fa257079f6b9469611dceb835ee8/cross-build/ethereum/cryptopp.sh#L47) and [oddly, 2](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/utils.sh#L232)

# jsonrpccpp:
- missing CXX [flags/options](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/libjson-rpc-cpp.sh#L40)

# secp256k1:
- CMake file [bug](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/secp256k1.sh#L18) (see [corresponding issue](https://github.com/ethereum/webthree-helpers/issues/68)]

# libweb3core:
- turning off Miniupnpc manually: [1](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/libweb3core.sh#L24) and [2](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/main.sh#L93)

# libethereum:
- turning off ethash-cl and ethash-cl Cpuid [manually](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/libethereum.sh#L22 and https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/main.sh#L92)
- std/boost [bug](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/libethereum.sh#L26) (do we have an issue for this? it was discussed on the cpp channel)
- BuildInfo/ConfigInfo [bug](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/libethereum.sh#L72) (do we have an issue for this? it was discussed on the cpp channel)

# webthree:
- turning off READLINE manually: [1](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/webthree.sh#L22) and [2](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/webthree.sh#L28)
- turning off jsengine/jsconsole [manually](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/webthree.sh#L23-L25)
- [Attach](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/webthree.sh#L31) bug (see [corresponding issue](https://github.com/ethereum/webthree/issues/69))
- missing [CXX_FLAGS](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/webthree.sh#L71)

**Comment by bobsummerwill** [comment]
Thanks - could you just kill this bug and make a GitHub issue per package?  Thanks!   Just cut-and-pasting these button points.

Titles:    Undo hacks for <x>.   Thanks!

**Comment by bobsummerwill** [comment]
"Undo hacks for X"

**Comment by bobsummerwill** [comment]
"turning off Miniupnpc manually" - Wasn't this the one you logged a Github issue for?

**Comment by bobsummerwill** [comment]
No.  It was Odd `-lOFF` flags in resulting Makefile I was thinking of ...

https://github.com/ethereum/libweb3core/issues/23

**Comment by bobsummerwill** [comment]
Pull request to address unconditional use of JSRemoteConsole in main.cpp of eth:
ethereum/webthree#89

**Comment by bobsummerwill** [comment]
@anthony-cros Please could you close https://github.com/ethereum/webthree-helpers/issues/68?

https://github.com/ethereum/webthree-helpers/pull/75 replaces it with a mergable fix.

**Comment by bobsummerwill** [comment]
Is the fundamental issue with all the OPTIONAL modules, @anthony-cros, that the semantics are "Look at my host machine's available libraries, and build different code depending on that"?   Where we do NOT want such implicit behavior, because our target machine might provide different answers?

So really for cross-building scenarios, you never want OPTIONAL modules, unless there was a way of controlling that on the command-line with parameterization?

**Comment by bobsummerwill** [comment]
Whereas the jsconsole and jsengine ones are just build system bugs of some kind, in that the C++ code itself can cope with them being on/off via #ifdefs, but we are perhaps missing an equivalent functional mechanism for skipping their build steps?

**Comment by bobsummerwill** [comment]
Actually, the other thing with the OPTIONAL modules is that they are assumed to be pre-installed and available, right?   They aren't being built within the native build process (V8 for example).  They are just package-installed.    Where we need to built them.

Aha!

**Comment by bobsummerwill** [comment]
Webthree "attach" bug has been addressed and the hack removed.   This was messed-up #ifdefs.

**Comment by anthony-cros** [comment]
crossed-off the list!

**Comment by bobsummerwill** [comment]
OK ... I'll make a complete fresh list of all the hacks here at some point today or tomorrow, after I finish my work on #42 , which has been a complete pig.    At least I have a better feeling for the shape of the whole thing now!

**Comment by bobsummerwill** [comment]
* Hack removal - Boost #67

**Comment by yep** [comment]
Please close this bug.

As suggested [above](https://github.com/doublethinkco/cpp-ethereum-cross/issues/11#issuecomment-157918318), having a separate issue for each item on this todo list is way more maintainable.

Just created issues #96 to #108 for this, please update status of each individual issue if neccessary.

**Comment by bobsummerwill** [comment]
Thanks!   Quick pass through them, and they looked correct.
Just merged the ones which got merged into cpp-ethereum.
