### ISSUE TITLE
lack of INSTALL doc

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [doublethinkco/cpp-ethereum-cross#122]
I just snagged the latest binaries for armhf. Unzipping gave a bin and lib directory with no indication of where they should go in the filesystem. There are lots of places to put binaries and libraries.

I tried to run eth which, of course, failed because it couldn't find any libraries but also gave no indication of where it was looking for them.

Please add an INSTALL file directing us where to put everything.

**Comment by bobsummerwill** [comment]
This project is inactive.
You can run `eth` from wherever you like.    I would just do something like the following myself:

    export LD_LIBRARY_PATH=~/eth/lib
    cd ~/eth/bin
    ./eth

I would suggest that you check out https://www.reddit.com/r/ethereum/comments/5o4nim/ethereum_on_arm_etharmbian_full_ethereum_node_is/?st=iyncydll&sh=84aa3f33, which is actively maintained.

Best wishes!

**Comment by ParaplegicRacehorse** [comment]
No support for CHIP (which is what I have). Geth works, but I'm a little weird about whether Go is on compute-speed parity with C. It would be interesting to see some comparison benchmarks.

No worries. Thanks, Bob@

**Comment by bobsummerwill** [comment]
No problem.

With `geth` you can also try out light client (LES) functionality, which will be orders-of-magnitude faster at syncing than a full-client `eth`.

**Comment by ParaplegicRacehorse** [comment]
`geth --light --mine` still wants a full blockchain downloaded. Annoying but not a software killer.

**Comment by bobsummerwill** [comment]
For CPU mining on the testnet, you mean?

Because mainnet needs a GPU.

**Comment by ParaplegicRacehorse** [comment]
No. For hashing on main. I assume that was intentional but why? It completely cuts out opportunity for ultra low power SBCs. The watts:FLOPS ratios are really bad for anything with a full size board and lots of extra components.

**Comment by bobsummerwill** [comment]
"needs a GPU" is just an economic reality.   You *can* CPU mine on the mainnet, but it won't be economic or enjoyable, because GPUs are vastly more efficient than CPUs for brute-force hashing.

Ethash has been designed to be ASIC-resistant, to avoid that centralization risk.

SBCs will be fine as nodes, but they aren't the best fit for mining.

**Comment by ParaplegicRacehorse** [comment]
I guess I'm stuck following consensus. It's not a terrible loss. There are other algos and other coins I can support with my [limited] hash. The blockchain is already too big to download in less time than it would take to snail-mail a snapshot and then update, so operating a node is out of the question. I still think the decision of whether it's feasible to cpu-mine should be left to the operator, though, and not taken from him/her by fiat.

**Comment by bobsummerwill** [comment]
To be clear - you *can* CPU mine on mainnet if you like.
It will just be utterly ineffective, and you will rarely (if ever) succeed in mining a block.

**Comment by ParaplegicRacehorse** [comment]
True. IF I have a full node to work from. Doesn't work with --light. As stated, it's faster to snail-mail and then update a blockchain snapshot than to download. That's another issue, though.
