### ISSUE TITLE
Error building xcompiler

### ISSUE THREAD

**Issue by hdsw** [doublethinkco/cpp-ethereum-cross#124]
Hi 
I am trying to run:

sudo ./build-xcompiler-armhf.sh

and I get the following error from the compiler:
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'linux-3.15.4'
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_kernel_get[scripts/build/kernel/linux.sh@741]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@582]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/xcompiler/ct-ng/install/share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 1:17.90)
[01:18] / make: *** [build] Error 1

There are no logs (or anyway I couldn't find them). Any ideas?
Michael

**Comment by bobsummerwill** [comment]
I am afraid this project is pretty much abandoned now.

What OS are you running on?

Aside - the xcompiler doesn't usually need rebuilding.   You can use the existing cross-compiler binaries as part of the other shell scripts which build the actual 'eth' binaries.

**Comment by bobsummerwill** [comment]
build-armel.sh, build-armel-apt.sh, build-armhf.sh, build-armhf-apt.sh etc.

**Comment by hdsw** [comment]
Thanks Bob, I will try that. I am running Ubuntu 16.04
