### ISSUE TITLE
Can't work at all to build armhf , need help

### ISSUE THREAD

**Issue by truelv** [doublethinkco/cpp-ethereum-cross#125]
@bobsummerwill  
**Error 1：It seems ubuntu wily is out of date and throwed into old-release** 
wyh@wyh-Z97X-UD3H:~/ETH/cpp-ethereum-cross$ sudo ./build-armhf.sh 
Sending build context to Docker daemon 2.144 MB
Step 1/13 : FROM ubuntu:wily
wily: Pulling from library/ubuntu
7dcf5a444392: Already exists 
759aa75f3cee: Already exists 
3fa871dc8a2b: Already exists 
224c42ae46e7: Already exists 
Digest: sha256:02521a2d079595241c6793b2044f02eecf294034f31d6e235ac4b2b54ffc41f3
Status: Downloaded newer image for ubuntu:wily
 ---> 9b9cb95443b5
Step 2/13 : MAINTAINER Bob Summerwill <bob@summerwill.net>
 ---> Running in 9ce97e4cc3de
 ---> d1edbf7e56a7
Removing intermediate container 9ce97e4cc3de
Step 3/13 : RUN apt-get update && apt-get install -y  autoconf=2.69-8     bzip2=1.0.6-8     cmake=3.2.2-2ubuntu3       git=1:2.5.0-1ubuntu0.2        m4=1.4.17-4   texinfo=6.0.0.dfsg.1-3      tree=1.7.0-3     unzip=6.0-17ubuntu1.2     wget=1.16.1-1ubuntu1
 ---> Running in 5bc6b12adf98
Ign http://archive.ubuntu.com wily InRelease
Ign http://archive.ubuntu.com wily-updates InRelease
Ign http://archive.ubuntu.com wily-security InRelease
Ign http://archive.ubuntu.com wily Release.gpg
Ign http://archive.ubuntu.com wily-updates Release.gpg
Ign http://archive.ubuntu.com wily-security Release.gpg
Ign http://archive.ubuntu.com wily Release
Ign http://archive.ubuntu.com wily-updates Release
Ign http://archive.ubuntu.com wily-security Release
Err http://archive.ubuntu.com wily/main Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily/restricted Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily/universe Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily/main amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily/universe amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-updates/main Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-updates/restricted Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-updates/universe Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-updates/main amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-updates/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-updates/universe amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-security/main Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-security/restricted Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-security/universe Sources
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-security/main amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-security/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
Err http://archive.ubuntu.com wily-security/universe amd64 Packages
  404  Not Found [IP: 91.189.88.161 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/main/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/restricted/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/universe/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/main/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/restricted/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/main/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/restricted/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/universe/source/Sources  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y  autoconf=2.69-8     bzip2=1.0.6-8     cmake=3.2.2-2ubuntu3       git=1:2.5.0-1ubuntu0.2        m4=1.4.17-4   texinfo=6.0.0.dfsg.1-3      tree=1.7.0-3     unzip=6.0-17ubuntu1.2     wget=1.16.1-1ubuntu1' returned a non-zero code: 100

**Error 2：**
wyh@wyh-Z97X-UD3H:~/ETH/cpp-ethereum-cross$ sudo ./build-xcompiler-armhf.sh 
Sending build context to Docker daemon 2.144 MB
Step 1/11 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
72c01b436656: Already exists 
65584f5f70ee: Already exists 
dc9874b52952: Already exists 
86656bbaa6fd: Already exists 
7fe6916ab382: Already exists 
Digest: sha256:cb96ec8eb632c873d5130053cf5e2548234e5275d8115a39394289d96c9963a6
Status: Downloaded newer image for ubuntu:14.04
 ---> c32fae490809
Step 2/11 : MAINTAINER Bob Summerwill <bob@summerwill.net>
 ---> Running in 4d62e97540c7
 ---> f745a0ce3320
Removing intermediate container 4d62e97540c7
Step 3/11 : RUN apt-get update
 ---> Running in 0cfa3e511130
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty-backports InRelease [65.9 kB]
Get:4 http://security.ubuntu.com trusty-security/universe Sources [104 kB]
Get:5 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:6 http://archive.ubuntu.com trusty-updates/universe Sources [268 kB]
Get:7 http://security.ubuntu.com trusty-security/main amd64 Packages [967 kB]
Get:8 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1387 kB]
Get:9 http://security.ubuntu.com trusty-security/restricted amd64 Packages [18.1 kB]
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [338 kB]
Get:11 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4722 B]
Get:12 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.4 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [634 kB]
Get:14 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [16.0 kB]
Get:15 http://archive.ubuntu.com trusty-backports/main amd64 Packages [14.7 kB]
Get:16 http://archive.ubuntu.com trusty-backports/restricted amd64 Packages [40 B]
Get:17 http://archive.ubuntu.com trusty-backports/universe amd64 Packages [52.5 kB]
Get:18 http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1392 B]
Get:19 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:20 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:21 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:22 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:23 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Get:24 http://archive.ubuntu.com trusty/multiverse amd64 Packages [169 kB]
Fetched 21.5 MB in 1min 10s (306 kB/s)
Reading package lists...
 ---> 598315fff842
Removing intermediate container 0cfa3e511130
Step 4/11 : RUN apt-get install -y   bzip2=1.0.6-5     git=1:1.9.1-1ubuntu0.1    tree=1.6.0-1   unzip=6.0-9ubuntu1.5    wget=1.15-1ubuntu1.14.04.1
 ---> Running in e7ae83d1dcfb
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1:1.9.1-1ubuntu0.1' for 'git' was not found
E: Version '1.15-1ubuntu1.14.04.1' for 'wget' was not found
The command '/bin/sh -c apt-get install -y   bzip2=1.0.6-5     git=1:1.9.1-1ubuntu0.1    tree=1.6.0-1   unzip=6.0-9ubuntu1.5    wget=1.15-1ubuntu1.14.04.1' returned a non-zero code: 100

**Error 3**：
README.md  is  out of date . It  is  not  appropriate  to  use  webthree-umbrella-cross  because  it  has  changed  into  cpp-ethereum-cross . It is so confused for a fresher to Ethereum .

Thx  a  lot .

**Comment by bobsummerwill** [comment]
This repository has been ummaintained for over 2 years.  If you would like to submit pull requests to fix it I would be happy to merge them?

What are you looking to get done?  I can likely suggest better alternatives.

**Comment by truelv** [comment]
@bobsummerwill   What I want is to port any one of the ethereum client to  SOC zynq7000 . Then I can  mining  ethereum!

**Comment by twhite00** [comment]
> @bobsummerwill What I want is to port any one of the ethereum client to SOC zynq7000 . Then I can mining ethereum!

so is there new idea been found , i want do the same thing

**Comment by twhite00** [comment]
> This repository has been ummaintained for over 2 years. If you would like to submit pull requests to fix it I would be happy to merge them?
> 
> What are you looking to get done? I can likely suggest better altern

> This repository has been ummaintained for over 2 years. If you would like to submit pull requests to fix it I would be happy to merge them?
> 
> What are you looking to get done? I can likely suggest better alternatives.

hi, can you give me some good idea on port light mode client on ARM devices, like zynq?

**Comment by bobsummerwill** [comment]
Check out Parity Ethereum and geth.  Those are the main two clients, and both have been ported to ARM.

**Comment by twhite00** [comment]
> Check out Parity Ethereum and geth. Those are the main two clients, and both have been ported to ARM.

ok , thx.

**Comment by twhite00** [comment]
> Check out Parity Ethereum and geth. Those are the main two clients, and both have been ported to ARM.

so is there light client mode like "geth --syncmode light" in cpp-ethereum(aleth) , we are trying to port aleth on other OS for embedded devices？

**Comment by truelv** [comment]
ethminer(version0.13.0rc9)  can be ported to arm . I have done it .

**Comment by twhite00** [comment]
> ethminer(version0.13.0rc9) can be ported to arm . I have don

> ethminer(version0.13.0rc9) can be ported to arm . I have done it .

OK,thx.
