### ISSUE TITLE
Generalize GMP/MHD-like builds (95% the same)

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/cpp-ethereum-cross#15]

**Comment by bobsummerwill** [comment]
So some utility .sh file with parameters for N of the similar external dependencies?

**Comment by anthony-cros** [comment]
yes, I even believe there are one or two more that are 90% similar, basically the usual suspects: configure+make+make install with little or no hacks

**Comment by bobsummerwill** [comment]
Right

**Comment by bobsummerwill** [comment]
Not worth bothering with.
