### ISSUE TITLE
Remove reference to $HOME variable

### ISSUE THREAD

**Issue by yep** [doublethinkco/cpp-ethereum-cross#95]
I think it's better not to enforce a specific directory structure on the user. There are at least two instances of hard coded paths:
- `BASE_DIR="${HOME?}/eth"`
- `XCOMPILER_DESTINATION_DIR="$HOME/x-tools"`

What is going to happen if one of these directories already exists?

I volunteer to make all paths relative in [this ios branch](https://github.com/yep/cpp-ethereum-cross/tree/ios).

**Comment by bobsummerwill** [comment]
Yes, the scripts make a number of assumptions which aren't great.

These flaws are unimportant within a Docker context, because the file-system there is throwaway.

If you would like to make changes to parameterize some of these things, that would be great.
